name: Build and Deploy Container App to Azure

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

env:
  REGISTRY_LOGIN_SERVER: dmoneycontainerregistry.azurecr.io  # Replace with your ACR login server
  IMAGE_BASE_NAME: dmoneyimage                               # Replace with your container image name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Fetch ACR credentials dynamically
    - name: Fetch ACR credentials
      id: acr-credentials
      run: |
        ACR_USERNAME=$(az acr credential show --name dmoneycontainerregistry --query "username" -o tsv)
        ACR_PASSWORD=$(az acr credential show --name dmoneycontainerregistry --query "passwords[0].value" -o tsv)
        echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
        echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

    # Step 4: Log in to Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}

    # Step 5: Set image version
    - name: Set image version
      id: image-version
      run: echo "::set-output name=version::$(date +'%Y%m%d%H%M%S')"

    # Step 6: Build and push the Docker image
    - name: Build and push image
      run: |
        docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}
        docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish  # This job runs after the build-and-publish job

    steps:
    # Step 1: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 2: Deploy Docker image to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: dmoneyWebApp  # Replace with your Azure Web App name
        images: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}
