name: Deploy Azure Resources

on:
  push:
    branches:
      - main # Trigger on push to the main branch
#Comment
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Azure CLI
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Deploy Bicep template
    - name: Deploy Bicep file
      run: |
        az deployment group create \
          --resource-group BCSAI2024-DEVOPS-STUDENTS-A-DEV \
          --template-file main.bicep \
          --parameters dmoneyContainerRegistryName=dmoneycontainerregistry \
                       dmoneyAppServicePlanName=dmoneyAppServicePlan \
                       dmoneyWebAppName=dmoneyWebApp \
                       location=westeurope
          --name main-$(date +%s) \
