name: Build and Deploy Container App to Azure

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  REGISTRY_NAME: dmoneycontainerregistry
  IMAGE_BASE_NAME: dmoneyimage
  WEB_APP_NAME: dmoneyWebApp
  LOCATION: westeurope

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy infrastructure using Bicep
      run: |
        az deployment group create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --template-file main.bicep \
          --parameters \
            dmoneyContainerRegistryName=${{ env.REGISTRY_NAME }} \
            dmoneyAppServicePlanName=dmoneyAppServicePlan \
            dmoneyWebAppName=${{ env.WEB_APP_NAME }} \
            location=${{ env.LOCATION }} \
          --mode Complete

    - name: Fetch ACR credentials
      run: |
        echo "REGISTRY_LOGIN_SERVER=$(az acr show --name ${{ env.REGISTRY_NAME }} --query "loginServer" -o tsv)" >> $GITHUB_ENV
        echo "REGISTRY_USERNAME=$(az acr credential show --name ${{ env.REGISTRY_NAME }} --query "username" -o tsv)" >> $GITHUB_ENV
        echo "REGISTRY_PASSWORD=$(az acr credential show --name ${{ env.REGISTRY_NAME }} --query "passwords[0].value" -o tsv)" >> $GITHUB_ENV

    - name: Fetch Key Vault secrets
      run: |
        echo "KEY_VAULT_NAME=$(az keyvault list --resource-group ${{ env.RESOURCE_GROUP }} --query "[0].name" -o tsv)" >> $GITHUB_ENV
        echo "ACR_SECRET_USERNAME=$(az keyvault secret show --name acr-username --vault-name ${{ env.KEY_VAULT_NAME }} --query value -o tsv)" >> $GITHUB_ENV
        echo "ACR_SECRET_PASSWORD=$(az keyvault secret show --name acr-password --vault-name ${{ env.KEY_VAULT_NAME }} --query value -o tsv)" >> $GITHUB_ENV

    - name: Get Service Principal ID
      run: |
        SP_ID=$(az ad sp show --id ${{ secrets.CLIENT_ID }} --query "id" -o tsv)
        echo "SERVICE_PRINCIPAL_ID=$SP_ID" >> $GITHUB_ENV

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Set image version
      run: echo "IMAGE_VERSION=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV

    - name: Ensure Docker is Installed
      run: docker --version

    - name: Build and push image
      run: |
        docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_VERSION }}
        docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_VERSION }}

    outputs:
      image: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy with Bicep
      run: |
        az deployment group create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --template-file main.bicep \
          --parameters ServicePrincipalId=${{ env.SERVICE_PRINCIPAL_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.WEB_APP_NAME }}
        images: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_VERSION }}
