name: Build and Deploy Container App to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

env:
  RESOURCE_GROUP: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  REGISTRY_NAME: dmoneycontainerregistry
  IMAGE_BASE_NAME: dmoneyimage
  WEB_APP_NAME: dmoneyWebApp
  LOCATION: westeurope

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Deploy infrastructure using Bicep
    - name: Deploy infrastructure using Bicep
      run: |
        az deployment group create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --template-file main.bicep \
          --parameters dmoneyContainerRegistryName=${{ env.REGISTRY_NAME }} \
                       dmoneyAppServicePlanName=dmoneyAppServicePlan \
                       dmoneyWebAppName=${{ env.WEB_APP_NAME }} \
                       keyVaultName=dmoneyKeyVault
                       location=${{ env.LOCATION }}

    # Step 4: Fetch ACR credentials dynamically
    - name: Fetch ACR credentials
      id: acr-credentials
      run: |
        echo "Fetching ACR credentials..."
        echo "::set-output name=login-server::$(az acr show --name ${{ env.REGISTRY_NAME }} --query "loginServer" -o tsv)"
        echo "::set-output name=username::$(az acr credential show --name ${{ env.REGISTRY_NAME }} --query "username" -o tsv)"
        echo "::set-output name=password::$(az acr credential show --name ${{ env.REGISTRY_NAME }} --query "passwords[0].value" -o tsv)"

    # Step 5: Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ steps.acr-credentials.outputs.login-server }}
        username: ${{ steps.acr-credentials.outputs.username }}
        password: ${{ steps.acr-credentials.outputs.password }}

    # Step 6: Set image version
    - name: Set image version
      id: image-version
      run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/})-$(date +'%Y.%m.%d.%H.%M')"

    # Step 7: Build and push Docker image
    - name: Build and push image
      run: |
        docker build . -t ${{ steps.acr-credentials.outputs.login-server }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}
        docker build . -t ${{ steps.acr-credentials.outputs.login-server }}/${{ env.IMAGE_BASE_NAME }}:${{ github.ref_name }}-latest
        docker push ${{ steps.acr-credentials.outputs.login-server }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}
        docker push ${{ steps.acr-credentials.outputs.login-server }}/${{ env.IMAGE_BASE_NAME }}:${{ github.ref_name }}-latest

    outputs:
      image: ${{ steps.acr-credentials.outputs.login-server }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job runs after build

    steps:
    # Step 1: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 2: Deploy Docker image to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.WEB_APP_NAME }}
        images: ${{ needs.build.outputs.image }}